services:
  openbooks:
    image: evanbuss/openbooks
    network_mode: bridge
    container_name: openbooks
    volumes:
     - $CONFIGDIR/openbooks:/config
     - $BOOKSDIR/openbooks:/books
    ports:
     - 8084:80
    restart: unless-stopped
    environment:
      PUID: $UID
      PGID: $GID
      TZ: US/Detroit
    command: --persist
  calibre-web:
    image: linuxserver/calibre-web:latest
    network_mode: bridge
    container_name: calibre-web
    volumes:
     - /etc/containers/calibre-web:/config
     - /media/all/books/calibre-web:/books
    ports:
     - 8083:8083
    restart: unless-stopped
    environment:
      PUID: $UID
      PGID: $GID
      TZ: America/Detroit
      DOCKER_MODS: linuxserver/calibre-web:calibre
  kavita:
    image: jvmilazz0/kavita:latest    # Using the stable branch from the offical repo.
    container_name: kavita
    volumes:
      - /media/all/books/kavita:/kavita/books
      - /media/all/books/kavita/data:/kavita/config     # Change './data if you want to have the config files in a different place.
                                  # /kavita/config must not be changed
    environment:
      TZ: America/Detroit
    ports:
     - 8085:5000 # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped
  email:
      image: jvmilazz0/kavitaemail:latest
      container_name: kavita-email
      environment:
        PUID: $UID
        PGID: $GID
      volumes:
         - /etc/containers/kavita-email:/app/config
      ports:
         - "5003:5003"
      restart: unless-stopped
