services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    network_mode: bridge
    container_name: calibre-web
    volumes:
     - $BOOKSCONFIGDIR:/config
     - $BOOKSDIR:/books
    ports:
     - 8083:8083
    restart: unless-stopped
    environment:
      PUID: $UID
      PGID: $GID
      TZ: US/Detroit
      DOCKER_MODS: linuxserver/calibre-web:calibre
