---
version: "2.1"
services:
  corekeeper:
    image: cajunbard/corekeeper:latest
    network_mode: bridge
    container_name: corekeeper
    volumes:
      - /etc/containers/corekeeper:/config
    ports:
      - 27015:27016/udp
    restart: unless-stopped
