---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    network_mode: bridge
    environment:
      - PUID=109
      - PGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/containers/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.rule=PathPrefix(`/tautulli`)
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: bridge
    ports:
      - 8989:8989
    environment:
      - PUID=109
      - GGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/sonarr:/config
      - /media/all/tv:/tv
      - /media/all/kids_tv:/kids_tv
      - /media/all/latenight/shows:/latenight_shows
      - /media/all/latenight/anime:/latenight_anime
      - /media/all/downloads/usenet:/downloads
      - /dev/rtc:/dev/rtc:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    network_mode: bridge
    environment:
      - LOG_LEVEL=debug
      - TZ=US/Detroit
    ports:
      - 5055:5055
    volumes:
      - /etc/containers/overseerr:/app/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.rule=PathPrefix(`/overseerr`)
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: bridge
    ports:
      - 8081:8080
    environment:
      - PUID=109
      - GGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/containers/sabnzbd:/config
      - /media/14tb/downloads/usenet-incomplete:/incomplete-downloads
      - /media/14tb/downloads/usenet:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=PathPrefix(`/sabnzbd`)
    restart: unless-stopped
  nzbhydra2:
    image: hotio/nzbhydra2:latest
    container_name: nzbhydra2
    network_mode: bridge
    ports:
      - 5076:5076
    environment:
      - PUID=109
      - GGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/containers/nzbhydra2:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.hydra.rule=PathPrefix(`/hydra`)
