---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=109
      - PGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/containers/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
