---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall-new
    environment:
      - PUID=109
      - PGID=100
      - TZ=US/Detroit
    volumes:
      - /etc/containers/heimdall:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.heimdall.loadbalancer.server.port=80
      - traefik.http.routers.heimdall.rule=PathPrefix(`/heimdall`)
  organizr:
    iamge: organizr/organizr
    container_name: organizr
    environment:
      - PUID=109
      - PGID=100
      - TZ=US/Detroit
    volume:
      - /etc/containers/organizr:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.organizr.loadbalancer.server.port=80
      - traefik.http.routers.organizr.rule=PathPrefix(`/organizr`)
