---
version: "2.1"
services:
  cloudflared:
    container_name: cloudflared
    image: 'cloudflare/cloudflared:${CLOUDFLARED_VERSION}' # version obtained from environment variable
    network_mode: host 
    command: 'tunnel --no-autoupdate run --token ${TOKEN}'
    user: root
    restart: unless-stopped
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - UID=109
      - GID=100
      - TZ=US/Detroit
      - DARK_MODE=true
    ports:
      - "8082:8081"
    volumes:
      - /media/all/downloads/metube:/downloads
