---
version: "2.1"
services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=109
      - PGID=100
      - TZ=US/Detroit
    volume:
      - /etc/containers/organizr:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.organizr.loadbalancer.server.port=80
      - traefik.http.routers.organizr.rule=PathPrefix(`/organizr`)
