---
services:
  cloudflared:
    container_name: cloudflared
    image: 'cloudflare/cloudflared:${CLOUDFLARED_VERSION}' # version obtained from environment variable
    network_mode: host 
    command: 'tunnel --no-autoupdate run --token ${TOKEN}'
    user: root
    restart: unless-stopped
  inadyn:
    image: troglobit/inadyn
    container_name: inadyn
    restart: unless-stopped
    volumes:
      - /etc/containers/inadyn:/etc
